#!/bin/sh

declare battery=`pmset -g batt | awk 'NR==2{print substr($3, 1, length($3) - 2)}'`

if [[ $battery -ge 50 ]]; then echo "#[bg=colour28] ♥ $battery"
elif [[ $battery -ge 20 ]]; then echo "#[bg=colour178,fg=black] ♥ $battery"
else echo "#[bg=colour160] ♥ $battery"
fi