#!/bin/sh

# memory_preassure
# system_profiler
declare total=`hostinfo | awk '/memory/ {  printf "%dGB",$4 }'`
declare percentage=`vm_stat | awk 'BEGIN{FS="[:]+"}{if(NR<7&&NR>1)sum+=$2; if(NR==2||NR==4||NR==5)free+=$2} END{printf "%3d%%\n",100*((sum - free)/sum)}'`

echo "$percentage of $total"